# Project Configuration
project:
  name: "Housing Price Prediction"
  version: "1.0"
  seed: 123

data:
  sample_size: 1500
  train_split: 0.8
  test_split: 0.2

preprocessing:
  outlier_method: "IQR"
  imputation_method: "median"
  scale_numeric: true
  center_numeric: true

models:
  linear_regression:
    method: "lm"
  
  random_forest:
    ntree: 500
    mtry_values: [2, 4, 6, 8]
    
  xgboost:
    nrounds: 100
    max_depth: [3, 6, 9]
    eta: [0.01, 0.1, 0.3]
    gamma: 0

cross_validation:
  method: "cv"
  number: 5
  repeats: 1